### ISSUE TITLE
Issue trying to use node-pandoc-promise with node v 12.13.0

### ISSUE THREAD

**Issue by alexsharaz** [asaf050/node-pandoc-promise#3]
Hi,
trying really hard to use the promis version of node-pandoc. Have managed to get node-pandoc working but unfortunately not this

Am trying to run the code below in a webdtorm environment
var express = require('express');
var router = express.Router();
var nodePandocPromise = require("node-pandoc-promise");

/* GET home page. */
router.get('/', function(req, res, next) {

    var src=" #Hello Bananas";
    var args = ['-f', 'markdown', '-t', 'html'];

    nodePandocPromise(src,args)
        .then(res=>{
            console.log(res);
        }).catch(err=>{
        console.error("oops",err);
    });

})

module.exports = router;

All I want to do is  convert a string to markdown format.
The catch isn;t hit  and the console.log just returns null
Packages installed, along wtih pandoc. and , as i said node-pandoc works fine.
This is all on a macos system
Any help appreciated

Rgfs
Alex

**Comment by asaf050** [comment]
Hey,
Thanks for reporting.
The issue has been resolved in version 0.0.6
